### ISSUE TITLE
Can we reproduce the high resolution spectrogram provided by Marcello?

### ISSUE THREAD

**Issue by bs** [earthspecies/spectral_hyperresolution#2] opened 2019-12-06 01:21 UTC
https://www.dropbox.com/s/1473non261zf9p9/dolphin%20hyper.png?dl=0

**Comment by aza** [comment] 2019-12-06 17:05
I’ve asked Marcelo for the audio file that generated the above file.

**Comment by radekosmulski** [comment] 2019-12-06 17:22
Will be very good to work towards reproducing that file.

I tried running `linear_reassignment` on the freesound data - with parameters where something is visible, it takes ~8 seconds to process the file. The implementation crashes on some files, haven't looked yet into why.

This is the notebook I [used](https://github.com/earthspecies/freesound/blob/master/05_Generate_spectograms.ipynb).

I am starting to think that maybe the hyperparameters I use are nowhere near where they should be to generate a high resolution spectogram like in the paper. Would be great to learn what values were used for `noct` and `over` (and to a lesser extent `tdeci`). I wonder what is the runtime of the algorithm in matlab on a GPU. There is a for loop in the center of the algorithm which is concerning.

Having an idea of the runtime in matlab both on the GPU and the CPU and of the range of values used would be super helpful.

**Comment by radekosmulski** [comment] 2019-12-06 17:42
`librosa` also dies on this data

**Comment by aza** [comment] 2019-12-06 19:09
I know that Marcelo used three different wavelets and merged them to make that graphic (the red, green, and blue have three different settings... it’s where they agree (white) that the non-artifact signal is.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by radekosmulski** [comment] 2019-12-06 21:48
Here is an [image](https://www.dropbox.com/preview/High%20Resolution%20Spectrogram/frg_cons_6.25_7.75_0.5.tiff?role=work) and an [audio file that it was generated from](https://www.dropbox.com/preview/High%20Resolution%20Spectrogram/fragment_6.25_7.75.wav?role=work) from the communcation with Marcelo. 

I'll hack a notebook on going from that audio file to a 3 channel image, might be I won't complete it today.

**Comment by radekosmulski** [comment] 2019-12-06 22:27
[matlab](https://github.com/earthspecies/spectral_hyperresolution/blob/master/from_wav_to_3channel_image_matlab.ipynb) and [python](https://github.com/earthspecies/spectral_hyperresolution/blob/master/from_wav_to_3channel_image.ipynb) notebooks

Matlab (using code from Marcelo) and python results seem similar - seems that the missing ingredient might be how the results are plotted (scale of pixel intensities)

**Comment by radekosmulski** [comment] 2019-12-06 22:49
This is the latest I got from the python notebook. 

![download](https://user-images.githubusercontent.com/2444926/70361391-aa959900-1881-11ea-9fc6-3bb043c0f87e.png)

- there is a lot of information there
- maybe different scale of pixel values, different color map
- what is most concerning is the frequency axis in the spectogram in Python, if the image that was shared with us has linear y axis, this would look like it is a log scale

**Comment by radekosmulski** [comment] 2019-12-06 22:59
Here is one of the channels from the tiff image for comparison
![image](https://user-images.githubusercontent.com/2444926/70361815-2fcd7d80-1883-11ea-87a6-4cfc635703ea.png)

The Python version took over 2 minutes to generate, was a bit worried that that could be the case, that with hyperparameters giving such results these spectograms will require a lot of compute.

In a sense these are all good results, there is a path forward and this just will require a bit more work. Seems isolating and tracking down the y axis scale issue should be the next focus point.

**Comment by radekosmulski** [comment] 2019-12-06 23:10
In the matlab file that was shared with us it says that the algorithm is
>frequency-line reassignment algorithm for frequency logscale constant Q

could it be that the visualizations were created with a different version of the algorithm? Anyhow, we can go to linear scale, that shouldn't be that much of a problem

**Comment by radekosmulski** [comment] 2019-12-07 19:05
Turns out going from logscale frequency to linear is a little bit more involved than I thought. I still think it is within reach but to get it right might require quite a bit of work. I sent an email to Marcelo with the generated representation asking if he could shed some additional light on what the scale of the axis in the representation from him is. If he replies and my suspicion ends up being correct, I'll ask him if maybe he would be so kind and share the code with us.

This would be the simplest way forward on this and would give me the best chance of getting the implementation with linear frequency of the y axis right.

**Comment by radekosmulski** [comment] 2019-12-19 06:05
done

**Closed as completed by radekosmulski** 2019-12-19 06:05 UTC

**Comment by radekosmulski** [comment] 2019-12-19 06:06
well, maybe this is not exactly done, but I think the intent was to verify that our implementation is correct, which I think has been achieved
